name: Build docs

on: [push, pull_request]

permissions:
    contents: write
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout source code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Check tags
          run: |
            git tag
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - name: Install poetry
          uses: abatilo/actions-poetry@v2
        - name: Install python dependencies
          run: poetry install -E docs
        - name: Build documentation
          run: |
            mkdir gh-pages
            touch gh-pages/.nojekyll
            poetry run sphinx-versioned -b "main, v0.2, v0.3" -m main
            cp -r docs/_build/* gh-pages/
        - name: Deploy documentation
          if: ${{ github.event_name == 'push' }}
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: gh-pages
            folder: gh-pages
